package proxim.be;

import java.sql.ResultSet;

import proxim.dao.Mdl_Variables;

public class PagosRecibosBE {
	public static String Gstr_ID_CASO=Mdl_Variables.Gstr_Ignore;
	public static String Gstr_ID_CASO_LOGIN=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENU=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_SUBMENU=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_SUBMENU1=Mdl_Variables.Gstr_Ignore;
	public static String GstrCMB_EMPRESA=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR1=Mdl_Variables.Gstr_Ignore;
	public static String GstrCMB_CUENTA_CARGO=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_NOMBRE_SOLICITUD=Mdl_Variables.Gstr_Ignore;
	public static String GstrCMB_TIPO_PAGO=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR=Mdl_Variables.Gstr_Ignore;
	public static String GstrCHK_TODOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ENVIAR=Mdl_Variables.Gstr_Ignore;
	public static String GstrCHK_TODOS1=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_CONTINUAR=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CLAVE=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CLAVE_DINAMICA=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_CONFIRMAR=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_CANCELAR_OPERACION=Mdl_Variables.Gstr_Ignore;
	public static String GstrFIRMAR=Mdl_Variables.Gstr_Ignore;
	public static String GstrFIRMANTE1=Mdl_Variables.Gstr_Ignore;
	public static String GstrFIRMANTE2=Mdl_Variables.Gstr_Ignore;
	public static String GstrFIRMANTE3=Mdl_Variables.Gstr_Ignore;
	public static String GstrESTADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_CERRAR_SESION=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_COLUMNA_ERROR=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENSAJE_ERROR=Mdl_Variables.Gstr_Ignore;
	public static String GstrRESULTADO_ESPERADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLBL_FECHA_OPERACION=Mdl_Variables.Gstr_Ignore;
	public static String GstrLBL_HORA_OPERACION=Mdl_Variables.Gstr_Ignore;
	public static String GstrLBL_MONTO_DOLARES=Mdl_Variables.Gstr_Ignore;
	public static String GstrLBL_MONTO_SOLES=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_ENVIAR_EMAIL_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CORREO_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENSAJE_CORREO_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ENVIAR_CORREO_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR_CORREO_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_EXCEL_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;  
	public static String GstrLNK_EXPORTAR_PDF_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;  
	public static String GstrLNK_IMPRIMIR_RESULTADO_FINAL=Mdl_Variables.Gstr_Ignore;  
	public static String GstrLNK_ENVIAR_EMAIL_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CORREO_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENSAJE_CORREO_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ENVIAR_CORREO_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR_CORREO_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_EXCEL_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_PDF_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_IMPRIMIR_PROCESADO=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_ENVIAR_EMAIL_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR_CORREO_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CORREO_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENSAJE_CORREO_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ENVIAR_CORREO_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_EXCEL_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_PDF_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_IMPRIMIR_BLOQUEADOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_ENVIAR_EMAIL_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ACEPTAR_CORREO_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_CORREO_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrTXT_MENSAJE_CORREO_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrBTN_ENVIAR_CORREO_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_EXCEL_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_EXPORTAR_PDF_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrLNK_IMPRIMIR_BLOQUEADOS_DETALLE=Mdl_Variables.Gstr_Ignore;
	public static String GstrCONSULTA_RECUDACION=Mdl_Variables.Gstr_Ignore;
	public static String GstrTAB_CONSULTA_RECUDACION=Mdl_Variables.Gstr_Ignore;
	public static String GstrCONSULTAR_SALDOS_MOVIMIENTOS=Mdl_Variables.Gstr_Ignore;
	public static String GstrOPERADOR=Mdl_Variables.Gstr_Ignore;
		
	public boolean obtenerCamposBD(ResultSet Rst_Funcionalidad, int intOpcion){
		boolean bandera = true; 
		try {
			//GENERAL
			Gstr_ID_CASO=Rst_Funcionalidad.getObject("ID_CASO") != null ? Rst_Funcionalidad.getString("ID_CASO") : Mdl_Variables.Gstr_Ignore;
			Gstr_ID_CASO_LOGIN=Rst_Funcionalidad.getObject("ID_CASO_LOGIN") != null ? Rst_Funcionalidad.getString("ID_CASO_LOGIN") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENU = Rst_Funcionalidad.getObject("TXT_MENU") != null ? Rst_Funcionalidad.getString("TXT_MENU") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_SUBMENU = Rst_Funcionalidad.getObject("TXT_SUBMENU") != null ? Rst_Funcionalidad.getString("TXT_SUBMENU") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_SUBMENU1 = Rst_Funcionalidad.getObject("TXT_SUBMENU1") != null ? Rst_Funcionalidad.getString("TXT_SUBMENU1") : Mdl_Variables.Gstr_Ignore;
			GstrCMB_EMPRESA = Rst_Funcionalidad.getObject("CMB_EMPRESA") != null ? Rst_Funcionalidad.getString("CMB_EMPRESA") : Mdl_Variables.Gstr_Ignore;
			GstrCMB_CUENTA_CARGO= Rst_Funcionalidad.getObject("CMB_CUENTA_CARGO") != null ? Rst_Funcionalidad.getString("CMB_CUENTA_CARGO") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_NOMBRE_SOLICITUD = Rst_Funcionalidad.getObject("TXT_NOMBRE_SOLICITUD") != null ? Rst_Funcionalidad.getString("TXT_NOMBRE_SOLICITUD") : Mdl_Variables.Gstr_Ignore;
			GstrCMB_TIPO_PAGO= Rst_Funcionalidad.getObject("CMB_TIPO_PAGO") != null ? Rst_Funcionalidad.getString("CMB_TIPO_PAGO") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ACEPTAR = Rst_Funcionalidad.getObject("BTN_ACEPTAR") != null ? Rst_Funcionalidad.getString("BTN_ACEPTAR") : Mdl_Variables.Gstr_Ignore;
			GstrCHK_TODOS= Rst_Funcionalidad.getObject("CHK_TODOS") != null ? Rst_Funcionalidad.getString("CHK_TODOS") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ENVIAR= Rst_Funcionalidad.getObject("BTN_ENVIAR") != null ? Rst_Funcionalidad.getString("BTN_ENVIAR") : Mdl_Variables.Gstr_Ignore;
			GstrCHK_TODOS1= Rst_Funcionalidad.getObject("CHK_TODOS1") != null ? Rst_Funcionalidad.getString("CHK_TODOS1") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_CONTINUAR = Rst_Funcionalidad.getObject("BTN_CONTINUAR") != null ? Rst_Funcionalidad.getString("BTN_CONTINUAR") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CLAVE= Rst_Funcionalidad.getObject("TXT_CLAVE") != null ? Rst_Funcionalidad.getString("TXT_CLAVE") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CLAVE_DINAMICA= Rst_Funcionalidad.getObject("TXT_CLAVE_DINAMICA") != null ? Rst_Funcionalidad.getString("TXT_CLAVE_DINAMICA") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_CONFIRMAR = Rst_Funcionalidad.getObject("BTN_CONFIRMAR") != null ? Rst_Funcionalidad.getString("BTN_CONFIRMAR") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_CANCELAR_OPERACION = Rst_Funcionalidad.getObject("BTN_CANCELAR_OPERACION") != null ? Rst_Funcionalidad.getString("BTN_CANCELAR_OPERACION") : Mdl_Variables.Gstr_Ignore;
			GstrFIRMAR= Rst_Funcionalidad.getObject("FIRMAR") != null ? Rst_Funcionalidad.getString("FIRMAR") : Mdl_Variables.Gstr_Ignore;
			GstrFIRMANTE1= Rst_Funcionalidad.getObject("FIRMANTE1") != null ? Rst_Funcionalidad.getString("FIRMANTE1") : Mdl_Variables.Gstr_Ignore;
			GstrFIRMANTE2= Rst_Funcionalidad.getObject("FIRMANTE2") != null ? Rst_Funcionalidad.getString("FIRMANTE2") : Mdl_Variables.Gstr_Ignore;
			GstrFIRMANTE3= Rst_Funcionalidad.getObject("FIRMANTE3") != null ? Rst_Funcionalidad.getString("FIRMANTE3") : Mdl_Variables.Gstr_Ignore;
			GstrESTADO= Rst_Funcionalidad.getObject("ESTADO") != null ? Rst_Funcionalidad.getString("ESTADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_CERRAR_SESION = Rst_Funcionalidad.getObject("LNK_CERRAR_SESION") != null ? Rst_Funcionalidad.getString("LNK_CERRAR_SESION") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_COLUMNA_ERROR= Rst_Funcionalidad.getObject("TXT_COLUMNA_ERROR") != null ? Rst_Funcionalidad.getString("TXT_COLUMNA_ERROR") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENSAJE_ERROR = Rst_Funcionalidad.getObject("TXT_MENSAJE_ERROR") != null ? Rst_Funcionalidad.getString("TXT_MENSAJE_ERROR") : Mdl_Variables.Gstr_Ignore;
			GstrRESULTADO_ESPERADO = Rst_Funcionalidad.getObject("RESULTADO_ESPERADO") != null ? Rst_Funcionalidad.getString("RESULTADO_ESPERADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_ENVIAR_EMAIL_RESULTADO_FINAL= Rst_Funcionalidad.getObject("LNK_ENVIAR_EMAIL_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("LNK_ENVIAR_EMAIL_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CORREO_RESULTADO_FINAL= Rst_Funcionalidad.getObject("TXT_CORREO_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("TXT_CORREO_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENSAJE_CORREO_RESULTADO_FINAL= Rst_Funcionalidad.getObject("TXT_MENSAJE_CORREO_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("TXT_MENSAJE_CORREO_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ENVIAR_CORREO_RESULTADO_FINAL= Rst_Funcionalidad.getObject("BTN_ENVIAR_CORREO_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("BTN_ENVIAR_CORREO_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ACEPTAR_CORREO_RESULTADO_FINAL= Rst_Funcionalidad.getObject("BTN_ACEPTAR_CORREO_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("BTN_ACEPTAR_CORREO_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_EXCEL_RESULTADO_FINAL= Rst_Funcionalidad.getObject("LNK_EXPORTAR_EXCEL_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_EXCEL_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_PDF_RESULTADO_FINAL= Rst_Funcionalidad.getObject("LNK_EXPORTAR_PDF_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_PDF_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_IMPRIMIR_RESULTADO_FINAL= Rst_Funcionalidad.getObject("LNK_IMPRIMIR_RESULTADO_FINAL") != null ? Rst_Funcionalidad.getString("LNK_IMPRIMIR_RESULTADO_FINAL") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_ENVIAR_EMAIL_PROCESADO = Rst_Funcionalidad.getObject("LNK_ENVIAR_EMAIL_PROCESADO") != null ? Rst_Funcionalidad.getString("LNK_ENVIAR_EMAIL_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CORREO_PROCESADO= Rst_Funcionalidad.getObject("TXT_CORREO_PROCESADO") != null ? Rst_Funcionalidad.getString("TXT_CORREO_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENSAJE_CORREO_PROCESADO= Rst_Funcionalidad.getObject("TXT_MENSAJE_CORREO_PROCESADO") != null ? Rst_Funcionalidad.getString("TXT_MENSAJE_CORREO_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ENVIAR_CORREO_PROCESADO= Rst_Funcionalidad.getObject("BTN_ENVIAR_CORREO_PROCESADO") != null ? Rst_Funcionalidad.getString("BTN_ENVIAR_CORREO_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ACEPTAR_CORREO_PROCESADO= Rst_Funcionalidad.getObject("BTN_ACEPTAR_CORREO_PROCESADO") != null ? Rst_Funcionalidad.getString("BTN_ACEPTAR_CORREO_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_EXCEL_PROCESADO = Rst_Funcionalidad.getObject("LNK_EXPORTAR_EXCEL_PROCESADO") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_EXCEL_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_PDF_PROCESADO = Rst_Funcionalidad.getObject("LNK_EXPORTAR_PDF_PROCESADO") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_PDF_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_IMPRIMIR_PROCESADO = Rst_Funcionalidad.getObject("LNK_IMPRIMIR_PROCESADO") != null ? Rst_Funcionalidad.getString("LNK_IMPRIMIR_PROCESADO") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_ENVIAR_EMAIL_BLOQUEADOS = Rst_Funcionalidad.getObject("LNK_ENVIAR_EMAIL_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("LNK_ENVIAR_EMAIL_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CORREO_BLOQUEADOS= Rst_Funcionalidad.getObject("TXT_CORREO_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("TXT_CORREO_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENSAJE_CORREO_BLOQUEADOS= Rst_Funcionalidad.getObject("TXT_MENSAJE_CORREO_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("TXT_MENSAJE_CORREO_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ENVIAR_CORREO_BLOQUEADOS= Rst_Funcionalidad.getObject("BTN_ENVIAR_CORREO_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("BTN_ENVIAR_CORREO_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ACEPTAR_CORREO_BLOQUEADOS= Rst_Funcionalidad.getObject("BTN_ACEPTAR_CORREO_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("BTN_ACEPTAR_CORREO_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_EXCEL_BLOQUEADOS = Rst_Funcionalidad.getObject("LNK_EXPORTAR_EXCEL_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_EXCEL_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_PDF_BLOQUEADOS = Rst_Funcionalidad.getObject("LNK_EXPORTAR_PDF_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_PDF_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_IMPRIMIR_BLOQUEADOS = Rst_Funcionalidad.getObject("LNK_IMPRIMIR_BLOQUEADOS") != null ? Rst_Funcionalidad.getString("LNK_IMPRIMIR_BLOQUEADOS") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_ENVIAR_EMAIL_BLOQUEADOS_DETALLE = Rst_Funcionalidad.getObject("LNK_ENVIAR_EMAIL_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("LNK_ENVIAR_EMAIL_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_CORREO_BLOQUEADOS_DETALLE= Rst_Funcionalidad.getObject("TXT_CORREO_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("TXT_CORREO_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrTXT_MENSAJE_CORREO_BLOQUEADOS_DETALLE= Rst_Funcionalidad.getObject("TXT_MENSAJE_CORREO_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("TXT_MENSAJE_CORREO_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ENVIAR_CORREO_BLOQUEADOS_DETALLE= Rst_Funcionalidad.getObject("BTN_ENVIAR_CORREO_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("BTN_ENVIAR_CORREO_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrBTN_ACEPTAR_CORREO_BLOQUEADOS_DETALLE= Rst_Funcionalidad.getObject("BTN_ACEPTAR_CORREO_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("BTN_ACEPTAR_CORREO_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_EXCEL_BLOQUEADOS_DETALLE = Rst_Funcionalidad.getObject("LNK_EXPORTAR_EXCEL_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_EXCEL_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_EXPORTAR_PDF_BLOQUEADOS_DETALLE = Rst_Funcionalidad.getObject("LNK_EXPORTAR_PDF_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("LNK_EXPORTAR_PDF_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrLNK_IMPRIMIR_BLOQUEADOS_DETALLE = Rst_Funcionalidad.getObject("LNK_IMPRIMIR_BLOQUEADOS_DETALLE") != null ? Rst_Funcionalidad.getString("LNK_IMPRIMIR_BLOQUEADOS_DETALLE") : Mdl_Variables.Gstr_Ignore;
			GstrCONSULTA_RECUDACION= Rst_Funcionalidad.getObject("CONSULTA_RECUDACION") != null ? Rst_Funcionalidad.getString("CONSULTA_RECUDACION") : Mdl_Variables.Gstr_Ignore;
			GstrTAB_CONSULTA_RECUDACION= Rst_Funcionalidad.getObject("TAB_CONSULTA_RECUDACION") != null ? Rst_Funcionalidad.getString("TAB_CONSULTA_RECUDACION") : Mdl_Variables.Gstr_Ignore;
			GstrCONSULTAR_SALDOS_MOVIMIENTOS= Rst_Funcionalidad.getObject("CONSULTAR_SALDOS_MOVIMIENTOS") != null ? Rst_Funcionalidad.getString("CONSULTAR_SALDOS_MOVIMIENTOS") : Mdl_Variables.Gstr_Ignore;
			GstrOPERADOR= Rst_Funcionalidad.getObject("OPERADOR") != null ? Rst_Funcionalidad.getString("OPERADOR") : Mdl_Variables.Gstr_Ignore;
			GstrCONSULTAR_SALDOS_MOVIMIENTOS= Rst_Funcionalidad.getObject("CONSULTAR_SALDOS_MOVIMIENTOS") != null ? Rst_Funcionalidad.getString("CONSULTAR_SALDOS_MOVIMIENTOS") : Mdl_Variables.Gstr_Ignore;
		} catch (Exception e) {
			bandera = false; 
			e.printStackTrace();
			System.out.println("Error:"  + e.getMessage());
		}
		return bandera;
	}	
}